version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_USER: test
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: hyneo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080